force-app/main/default/objects/Opportunity/fields/S3_Archival_URL__c.field-meta.xml
<CustomField>
    <fullName>S3_Archival_URL__c</fullName>
    <label>S3 Archival URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/s3bucket__c.field-meta.xml
<CustomField>
    <fullName>s3bucket__c</fullName>
    <label>s3bucket</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/s3filename__c.field-meta.xml
<CustomField>
    <fullName>s3filename__c</fullName>
    <label>s3filename__c</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/s3key__c.field-meta.xml
<CustomField>
    <fullName>s3key__c</fullName>
    <label>s3key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/s3downloadController.cls
public class s3downloadController {
    @AuraEnabled
    public static Opportunity getOpportunity(Id id) {
        Opportunity opportunity = [
            SELECT Id, Account.Name, Name, CloseDate,
            Amount, Description, StageName, s3key__c, s3filename__c,
            s3bucket__c, S3_Archival_URL__c
            FROM Opportunity
            WHERE Id =: id
        ];
        return opportunity;
    }
}